name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: >-
          --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for testing
        run: |
          docker build -t jaicharan/react-test:latest -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: |
          docker run -e CI=true jaicharan/react-test:latest npm test

      - name: Build additional Docker images
        run: |
          docker build -t jaicharan/multi-client:latest -f ./client/Dockerfile ./client
          docker build -t jaicharan/multi-nginx:latest -f ./nginx/Dockerfile ./nginx
          docker build -t jaicharan/multi-worker:latest -f ./worker/Dockerfile ./worker
          docker build -t jaicharan/multi-server:latest -f ./server/Dockerfile ./server
